services:
  postgres:
    image: postgres:15-alpine
    container_name: news_db_cont
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news
    ports:
      - "5429:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d


volumes:
  postgres_data: