package com.news;

import java.io.FileInputStream;
import java.util.List;
import java.util.Properties;

public class ConfigLoader {

    public static List<String> countries() {
        return List.of("Europe",
                "Asia",
                "Latin America",
                "Africa",
                "UK",
                "Western Europe",
                "Eastern Europe",
                "Northern Europe",
                "Southern Europe",
                "France",
                "Germany",
                "Benelux",
                "Switzerland",
                "Poland",
                "Czech Republic",
                "Hungary",
                "Ukraine",
                "Romania",
                "Scandinavia",
                "Finland",
                "Baltic States",
                "Italy",
                "Spain",
                "Portugal",
                "Greece",
                "Malta",
                "East Asia",
                "Southeast Asia",
                "South Asia",
                "Central Asia",
                "West Asia",
                "China",
                "Japan",
                "South Korea",
                "Mongolia",
                "Taiwan",
                "Indonesia",
                "Thailand",
                "Vietnam",
                "Malaysia",
                "Philippines",
                "India",
                "Pakistan",
                "Bangladesh",
                "Sri Lanka",
                "Nepal",
                "Kazakhstan",
                "Uzbekistan",
                "Kyrgyzstan",
                "Tajikistan",
                "Turkey",
                "Iran",
                "Saudi Arabia",
                "UAE",
                "Israel",
                "Mexico & Central America",
                "Caribbean",
                "South America",
                "Mexico",
                "Guatemala",
                "Honduras",
                "El Salvador",
                "Costa Rica",
                "Cuba",
                "Dominican Republic",
                "Puerto Rico",
                "Jamaica",
                "Brazil",
                "Argentina",
                "Colombia",
                "Peru",
                "Chile",
                "North Africa",
                "West Africa",
                "East Africa",
                "Central Africa",
                "Southern Africa",
                "Egypt",
                "Morocco",
                "Algeria",
                "Libya",
                "Tunisia",
                "Nigeria",
                "Ghana",
                "Ivory Coast",
                "Senegal",
                "Mali",
                "Ethiopia",
                "Kenya",
                "Tanzania",
                "Uganda",
                "Somalia",
                "Democratic Republic of the Congo",
                "Republic of the Congo",
                "Chad",
                "Cameroon",
                "South Africa",
                "Namibia",
                "Botswana",
                "Zimbabwe",
                "Mozambique",
                "England",
                "Scotland",
                "Wales",
                "Northern Ireland",
                "London",
                "Manchester",
                "Birmingham",
                "Liverpool",
                "Edinburgh",
                "Glasgow",
                "Cardiff",
                "Belfast");
    }

    public static String getApiKey() {
        try {
            Properties props = new Properties();
            FileInputStream in = new FileInputStream("config.properties");
            props.load(in);
            return props.getProperty("HF_API_KEY");
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
}

